# Generated by Django 5.1.2 on 2024-10-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0004_courses'),
       # ('payment_processing', '0002_alter_payment_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
